---
title: "W3-Bootstrap"
format: pdf
editor: visual
---

## Learning Objective

Use the base functions to construct bootstrap replications.

## Demonstration of bootstrap sampling for parameter estimation 

```{r sampling}
library(MASS) 
# suppose the true population is as follows: 
set.seed(2) 
population <- mvrnorm(10000, mu = c(0, 0), Sigma = matrix(c(1, 0.5, 0.5, 1.25), ncol = 2), empirical = TRUE)

plot(population) 
```

```{r}
# Sampling from the population
par(mfrow=c(2, 2))
for (i in 1:4) {
  s <- population[sample(x=1:nrow(population), size = 100, replace = TRUE),]
  plot(s, pch = 16, col = "cyan4", xlab = "X", ylab = "Y")
}
```

```{r}
# Sampling 1000 times from the population and estimating alpha
alpha.hats <- c()

for (i in 1:1000) {
  s <- population[sample(x=1:nrow(population), size = 100, replace = TRUE),]
  sigma.hats <- apply(s, 2, var) 
  cor.hat <- cor(s[,1], s[,2])
  alpha.hats <- c(alpha.hats, (sigma.hats[2] - cor.hat) / (sigma.hats[1] + sigma.hats[2] - 2*cor.hat))
}

```

```{r}
# Suppose we only have one sample from the population and now need to rely on bootstrap approach 
s <- population[sample(x=1:nrow(population), size = 100, replace = TRUE),]
# bootstrap sampling from the single sample data and estimating alpha
bs.alpha.hats <- c() 
for (i in 1:1000) {
  bs <- s[sample(x = 1:nrow(s), size = nrow(s), replace = TRUE,)]
  bs.sigma.hats <- apply(bs, 2, var)
  bs.cor.hat <- cor(bs[,1], bs[,2])
  bs.alpha.hats <- c(bs.alpha.hats, (bs.sigma.hats[2] - bs.cor.hat) / (bs.sigma.hats[1] + bs.sigma.hats[2] - 2*bs.cor.hat))
}
```

```{r}
# plot and compare alpha estimated from sampling from true population and bootstrap sampling
par(mfrow=c(1, 3))
hist(alpha.hats, col="gold") 
abline(v=0.6, col="pink", lwd=2) 
hist(bs.alpha.hats, col="cyan4")
abline(v=0.6, col="pink", lwd =2)
boxplot(alpha.hats, bs.alpha.hats, ylim=c(0.3, 0.9), col=c("gold", "cyan4"))
abline(h=0.6, col="pink", lwd=2)
```
